// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wotohsamzagjxfnkwsdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvdG9oc2FtemFnanhmbmt3c2RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzA2MzksImV4cCI6MjA2NTUwNjYzOX0.YwpomPDOy_OvpIf57DF1pCMMVB_wMyld3hf2-kB3dxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);